<?php

return [
    'shop' => [
        'auth_partner' => 'GET',
        'cancel_auth_partner' => 'GET',
        'get_shop_info' => 'GET',
        'get_profile' => 'GET',
        'update_profile' => 'POST',
        'get_warehouse_detail' => 'GET',
    ],
    'auth' => [
        'get_access_token' => 'POST', //'/api/v2/auth/token/get',
        'refresh_access_token' =>  'POST', //'/api/v2/auth/access_token/get',
    ],
    'media_space' => [
        'init_video_upload' => 'POST',
        'upload_video_part' =>  'ATTACH',
        'complete_video_upload' => 'POST',
        'get_video_upload_result' =>  'GET',
        'cancel_video_upload' => 'POST',
        'upload_image' =>  'ATTACH',
    ],
    'order' => [
        'get_order_list' => 'GET',
        'get_shipment_list' => 'GET',
        'get_order_detail' => 'GET',
        'split_order' => 'POST',
        'unsplit_order' => 'POST',
        'cancel_order' => 'POST',
        'handle_buyer_cancellation' => 'POST',
        'set_note' => 'POST',
        'add_invoice_data' => 'POST',
        'get_pending_buyer_invoice_order_list' => 'GET',
        'upload_invoice_doc' => 'POST',
        'download_invoice_doc' => 'GET',
        'get_buyer_invoice_info' => 'POST',
    ],
    'logistics' => [
        'get_shipping_parameter' => 'GET',
        'get_tracking_number' => 'GET',
        'ship_order' => 'POST',
        'update_shipping_order' => 'POST',
        'get_shipping_document_parameter' => 'POST',
        'create_shipping_document' => 'POST',
        'get_shipping_document_result' => 'POST',
        'download_shipping_document' => 'POST',
        'get_tracking_info' => 'GET',
        'get_address_list' => 'GET',
        'set_address_config' => 'POST',
        'delete_address' => 'POST',
        'get_channel_list' => 'GET',
        'update_channel' => 'POST',
        'batch_ship_order' => 'POST',
        'get_shipping_document_data_info' => 'POST',
    ],
    'product' => [
        'get_category' => 'GET',
        'get_attributes' => 'GET',
        'get_attribute_tree' => 'GET',
        'get_brand_list' => 'GET',
        'get_dts_limit' => 'GET',
        'get_item_limit' => 'GET',
        'get_item_list' => 'GET',
        'get_item_base_info' => 'GET',
        'get_item_extra_info' => 'GET',
        'add_item' => 'POST',
        'update_item' => 'POST',
        'delete_item' => 'POST',
        'init_tier_variation' => 'POST',
        'update_tier_variation' => 'POST',
        'get_model_list' => 'GET',
        'add_model' => 'POST',
        'update_model' => 'POST',
        'delete_model' => 'POST',
        'support_size_chart' => 'GET',
        'update_size_chart' => 'POST',
        'unlist_item' => 'POST',
        'update_price' => 'POST',
        'update_stock' => 'POST',
        'boost_item' => 'POST',
        'get_boosted_list' => 'GET',
        'get_item_promotion' => 'GET',
        'update_sip_item_price' => 'POST',
        'search_item' => 'GET',
        'get_comment' => 'GET',
        'reply_comment' => 'POST',
        'category_recommend' => 'GET',
        'register_brand' => 'POST',
        'get_recommend_attribute' => 'GET',
        'get_product_info' => 'POST',
        'get_weight_recommendation' => 'POST',
        'get_size_chart_list' => 'GET',
        'get_size_chart_detail' => 'GET',
    ],
    'first_mile' => [
        'get_unbind_order_list' => 'GET',
        'get_detail' => 'GET',
        'generate_first_mile_tracking_number' => 'POST',
        'bind_first_mile_tracking_number' => 'POST',
        'unbind_first_mile_tracking_number' => 'POST',
        'get_tracking_number_list' => 'GET',
        'get_waybill' => 'POST',
        'get_channel_list' => 'GET',
    ],
    'payment' => [
        'get_escrow_detail' => 'GET',
        'set_shop_installment_status' => 'POST',
        'get_payout_detail' => 'GET',
        'set_item_installment_status' => 'POST',
        'get_item_installment_status' => 'POST',
        'get_payment_method_list' => 'GET',
        'get_wallet_transaction_list' => 'GET',
        'get_escrow_list' => 'GET',
    ],
    'discount' => [
        'add_discount' => 'POST',
        'add_discount_item' => 'POST',
        'delete_discount' => 'POST',
        'delete_discount_item' => 'POST',
        'get_discount' => 'GET',
        'get_discount_list' => 'GET',
        'update_discount' => 'POST',
        'update_discount_item' => 'POST',
        'end_discount' => 'POST',
    ],
    'bundle_deal' => [
        'add_bundle_deal' => 'POST',
        'add_bundle_deal_item' => 'POST',
        'get_bundle_deal_list' => 'GET',
        'get_bundle_deal' => 'GET',
        'get_bundle_deal_item' => 'GET',
        'update_bundle_deal' => 'POST',
        'update_bundle_deal_item' => 'POST',
        'end_bundle_deal' => 'POST',
        'delete_bundle_deal' => 'POST',
        'delete_bundle_deal_item' => 'POST',
    ],
    'add_on_deal' => [
        'add_add_on_deal' => 'POST',
        'add_add_on_deal_main_item' => 'POST',
        'add_add_on_deal_sub_item' => 'POST',
        'delete_add_on_deal' => 'POST',
        'delete_add_on_deal_main_item' => 'POST',
        'delete_add_on_deal_sub_item' => 'POST',
        'get_add_on_deal_list' => 'GET',
        'get_add_on_deal' => 'GET',
        'get_add_on_deal_main_item' => 'GET',
        'get_add_on_deal_sub_item' => 'GET',
        'update_add_on_deal' => 'POST',
        'update_add_on_deal_main_item' => 'POST',
        'update_add_on_deal_sub_item' => 'POST',
        'end_add_on_deal' => 'POST',
    ],
    'voucher' => [
        'add_voucher' => 'POST',
        'delete_voucher' => 'POST',
        'end_voucher' => 'POST',
        'update_voucher' => 'POST',
        'get_voucher' => 'GET',
        'get_voucher_list' => 'GET',
    ],
    'follow_prize' => [
        'add_follow_prize' => 'POST',
        'delete_follow_prize' => 'POST',
        'end_follow_prize' => 'POST',
        'update_follow_prize' => 'POST',
        'get_follow_prize_detail' => 'GET',
        'get_follow_prize_list' => 'GET',
    ],
    'top_picks' => [
        'get_top_picks_list' => 'GET',
        'add_top_picks' => 'POST',
        'update_top_picks' => 'POST',
        'delete_top_picks' => 'POST',
    ],
    'shop_category' => [
        'add_shop_category' => 'POST',
        'get_shop_category_list' => 'GET',
        'delete_shop_category' => 'POST',
        'update_shop_category' => 'POST',
        'add_item_list' => 'POST',
        'get_item_list' => 'GET',
        'delete_item_list' => 'POST',
    ],
    'returns' => [
        'get_return_detail' => 'GET',
        'get_return_list' => 'GET',
        'confirm' => 'POST',
        'dispute' => 'POST',
        'get_available_solutions' => 'GET',
        'offer' => 'POST',
        'accept_offer' => 'POST',
        'convert_image' => 'POST',
        'upload_proof' => 'POST',
        'query_proof' => 'POST',
    ],
    'public' => [
        'get_token_by_resend_code' =>  'POST',
        'get_refresh_token_by_upgrade_code' =>  'POST',
        'get_shops_by_partner' =>  'GET',
        'get_merchants_by_partner' =>  'GET',
        'get_shopee_ip_ranges' =>  'GET',
    ],
    'merchant' => [
        'get_merchant_info' =>  'GET',
        'get_shop_list_by_merchant' =>  'GET',
        'get_merchant_warehouse_location_list' =>  'GET',
    ],
    'push' => [
        'set_app_push_config' =>  'POST',
        'get_app_push_config' =>  'GET',
    ],
    'account_health' => [
        'shop_performance' =>  'GET',
        'shop_penalty' =>  'GET',
    ],
];
